-- This script creates a view that provides a summary of customer trips, including customer details, trip status, and fare information.
CREATE OR REPLACE VIEW VW_CUSTOMER_TRIPS AS
SELECT 
    C.FIRST_NAME AS CUSTOMER_FIRST_NAME, 
    C.LAST_NAME AS CUSTOMER_LAST_NAME,
    S.STATUS AS TRIP_STATUS,
    T.START_TIME,
    T.END_TIME,
    T.PICKUP_LOCATION,
    T.DROPOFF_LOCATION,
    T.DISTANCE_MILES,
    T.TOTAL_FARE AS FARE,
    T.TRIP_RATING,
    RT.TYPE AS RIDE_TYPE
FROM TRIP T
JOIN CUSTOMER C ON T.CUSTOMER_ID = C.CUSTOMER_ID
JOIN VEHICLE V ON T.VECHICLE_ID = V.VECHICLE_ID
JOIN RIDE_TYPE RT ON V.RIDE_TYPE_ID = RT.RIDE_TYPE_ID
JOIN TRIP_STATUS TS ON TS.TRIP_ID = T.TRIP_ID
JOIN STATUS_MASTER S ON TS.STATUS_ID = S.STATUS_ID
WHERE TS.LAST_UPDATED_AT = (
    SELECT MAX(TS_SUB.LAST_UPDATED_AT)
    FROM TRIP_STATUS TS_SUB
    WHERE TS_SUB.TRIP_ID = T.TRIP_ID
);

--test view
--SELECT * FROM VW_CUSTOMER_TRIPS;
