-- Create a view to get the trip history of drivers
CREATE OR REPLACE VIEW VW_DRIVER_TRIPS AS
SELECT
  T.TRIP_ID,
  C.FIRST_NAME || ' ' || C.LAST_NAME AS CUSTOMER,
  D.FIRST_NAME AS DRIVER_FIRST_NAME,
  D.LAST_NAME AS DRIVER_LAST_NAME,
  T.START_TIME,
  T.END_TIME,
  T.PICKUP_LOCATION,
  T.DROPOFF_LOCATION,
  T.TOTAL_FARE AS EARNINGS,
  SM.STATUS AS TRIP_STATUS
FROM TRIP T
JOIN CUSTOMER C ON T.CUSTOMER_ID = C.CUSTOMER_ID
JOIN RIDE_TYPE RT ON T.RIDE_TYPE_ID = RT.RIDE_TYPE_ID
JOIN VEHICLE V ON RT.RIDE_TYPE_ID = V.RIDE_TYPE_ID
JOIN DRIVER D ON V.DRIVER_ID = D.DRIVER_ID
JOIN TRIP_STATUS TS ON T.TRIP_ID = TS.TRIP_ID
JOIN Status_Master SM ON TS.STATUS_ID = SM.STATUS_ID
WHERE TS.LAST_UPDATED_AT = (
    SELECT MAX(TS_SUB.LAST_UPDATED_AT)
    FROM TRIP_STATUS TS_SUB
    WHERE TS_SUB.TRIP_ID = T.TRIP_ID
)
ORDER BY 2,3;
--AND D.DRIVER_ID = 1;  //Add a specific driver id to get the trip history for that driver

-- Test the view
--SELECT * FROM VW_DRIVER_TRIPS;