-- Find the drivers who have registered and not added the license number
CREATE OR REPLACE VIEW VW_DRIVERS_WITHOUT_LICENSE AS
SELECT 
    D.DRIVER_ID,
    D.FIRST_NAME AS DRIVER_FIRST_NAME,
    D.LAST_NAME AS DRIVER_LAST_NAME,
    D.EMAIL,
    D.PHONE_NUMBER,
    D.CREATED_AT AS REGISTRATION_DATE
FROM DRIVER D
WHERE D.LICENSE_NUMBER IS NULL
ORDER BY D.CREATED_AT DESC;

-- Test the view
--SELECT * FROM VW_DRIVERS_WITHOUT_LICENSE;