-- Find trips which have less than 3 rating (Support team)/ (Fleet manager) to check why that trip is rated poorly
CREATE OR REPLACE VIEW LOW_RATED_TRIPS AS
SELECT 
    T.TRIP_ID,
    C.FIRST_NAME AS CUSTOMER_FIRST_NAME,
    C.LAST_NAME AS CUSTOMER_LAST_NAME,
    D.FIRST_NAME AS DRIVER_FIRST_NAME,
    D.LAST_NAME AS DRIVER_LAST_NAME,
    T.PICKUP_LOCATION,
    T.DROPOFF_LOCATION,
    T.DISTANCE_MILES,
    T.TOTAL_FARE,
    T.TRIP_RATING,
    T.START_TIME,
    T.END_TIME
FROM TRIP T
JOIN CUSTOMER C ON T.CUSTOMER_ID = C.CUSTOMER_ID
JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
JOIN DRIVER D ON V.DRIVER_ID = D.DRIVER_ID
WHERE T.TRIP_RATING <=3;

--test view
--SELECT * FROM LOW_RATED_TRIPS