-- This view retrieves all requested trips along with customer details and ride type.
CREATE OR REPLACE VIEW VW_REQUESTED_TRIPS AS
SELECT 
    T.TRIP_ID,
    C.FIRST_NAME AS CUSTOMER_FIRST_NAME,
    C.LAST_NAME AS CUSTOMER_LAST_NAME,
    T.PICKUP_LOCATION AS PICKUP_ADDRESS,
    T.PICKUP_ZIPCODE,
    T.DROPOFF_LOCATION AS DROPOFF_ADDRESS,
    T.DROPOFF_ZIPCODE,
    RT.TYPE AS RIDE_TYPE
FROM TRIP T
JOIN CUSTOMER C ON T.CUSTOMER_ID = C.CUSTOMER_ID
JOIN VEHICLE V ON T.VEHICLE_ID = V.VEHICLE_ID
JOIN RIDE_TYPE RT ON V.RIDE_TYPE_ID = RT.RIDE_TYPE_ID
JOIN TRIP_STATUS TS ON TS.TRIP_ID = T.TRIP_ID
JOIN STATUS_MASTER S ON TS.STATUS_ID = S.STATUS_ID
WHERE S.STATUS = 'Requested'
  AND TS.LAST_UPDATED_AT = (
      SELECT MAX(TS_SUB.LAST_UPDATED_AT)
      FROM TRIP_STATUS TS_SUB
      WHERE TS_SUB.TRIP_ID = T.TRIP_ID
  );

--Test view
--SELECT * FROM VW_REQUESTED_TRIPS;