GRANT EXECUTE ON PKG_TRIP_CANCELLATION TO APP_CUSTOMER, UBER_DRIVER;
GRANT EXECUTE ON PKG_TRIP_COMPLETION TO UBER_DRIVER;
GRANT EXECUTE ON PKG_TRIP_IN_PROGRESS TO UBER_DRIVER;
GRANT EXECUTE ON PKG_TRIP_REQUEST TO APP_CUSTOMER, FLEET_MANAGEMENT;


GRANT EXECUTE ON insert_driver TO UBER_DRIVER, FLEET_MANAGEMENT;
GRANT EXECUTE ON APPLICATION_ADMIN.INSERT_VEHICLE TO UBER_DRIVER;

GRANT EXECUTE ON APPLICATION_ADMIN.ADD_CUSTOMER_FEEDBACK TO APP_CUSTOMER;
GRANT EXECUTE ON APPLICATION_ADMIN.ADD_DRIVER_FEEDBACK TO UBER_DRIVER;

GRANT EXECUTE ON INSERT_CUSTOMER TO APP_CUSTOMER;